Angielozanogr
DeustoPWEB2018/proyectoweb-migraciones pull request #7
Opened 2018-10-15 14:00 UTC by angielozanogr

2018-10-19 22:59 UTC, LisandroToledo requested changes
@angielozanogr @mberasategi @estelleroques

2018-10-19 22:59 UTC, LisandroToledo commented on 1-estrategia/README.md
> +__Quien:__ El público al que nos dirigimos son migrantes entre 20 y 45 años que llegan al País Vasco. Nos hemos centrado en esta franja de edad, ya que según una encuesta realizada por el Gobierno Va
```suggestion
__Quien:__ El público al que nos dirigimos son migrantes forzados de entre 20 y 45 años que llegan al País Vasco. Nos hemos centrado en esta franja de edad, ya que según una encuesta realizada por el Gobierno Vasco en el año 2010 el 47% de los inmigrantes que llegan tienen entre 25 y 44 años, un 34% son menores de 25 años y tan solo el 19% son mayores de 45 años. Por esta razón, hemos concretado nuestro publico objetivo en este rango de edad, ya que además son las personas que más uso hacen de las plataformas web, redes sociales y aplicaciones para móviles ó tablets.
```

2018-10-19 22:59 UTC, LisandroToledo commented on 1-estrategia/README.md
> +__PRODUCTO:__ Es una plataforma web informativa denominada *Aupa→  El Diario que te ayuda*,  consiste en ordenar la información relevante de  instituciones y organizaciones que trabajan para integrar
```suggestion
__PRODUCTO:__ Es una plataforma web informativa denominada *Aupa→  La plataforma que te ayuda*,  consiste en ordenar la información relevante de  instituciones publicas y ONGs que trabajan para integrar a los migrantes forzados por cuestiones políticas, económicas, guerras (...). Eventualmente, crearemos contenido que complemente lo anterior para cumplir los objetivos del producto.
```

2018-10-19 22:59 UTC, LisandroToledo commented on 1-estrategia/README.md
> +Queremos que nuestros usuarios ingresen con inquietudes y salgan con ellas resueltas, es decir, cuando el migrante llega a su lugar de destino se encuentra en lo que denominaremos el punto cero, sin
```suggestion
Buscamos ser ese facilitador para los inmigrantes forzados que pueda brindarle un marco formal ó camino a seguir para resolver sus necesidades e inquietudes con el menor plazo de tiempo posible.
De un modo simplificado, partiremos dando por sentado una situación común a todos los inmigrantes forzados la que denominaremos "punto cero" con la siguiente característica: inmigrante forzado que llega al Pais Vasco sin tener resuelto de antemano los papeles migratorios, alojamiento, alimentación, educación, trabajo, atención sanitaria, red de vínculos sociales, etc. Desde allí, existirán "x pasos", que prevén, facilitar el camino a seguir para la resolución ó superación de todas las necesidades que tienen hasta alcanzar el paso final que les permita la plena inserción en la comunidad vasca.
Desglosar el proceso en pasos permitirá que cada inmigrante forzado pueda partir desde el paso que se adapte a su situación particular y luego si, continuar con los pasos que restan.
```

2018-10-21 16:01 UTC, estelleroques commented on 1-estrategia/README.md
> +__Quien:__ El público al que nos dirigimos son migrantes entre 20 y 45 años que llegan al País Vasco. Nos hemos centrado en esta franja de edad, ya que según una encuesta realizada por el Gobierno Va
Cambios realizados

2018-10-21 16:03 UTC, estelleroques commented on 1-estrategia/README.md
> +__PRODUCTO:__ Es una plataforma web informativa denominada *Aupa→  El Diario que te ayuda*,  consiste en ordenar la información relevante de  instituciones y organizaciones que trabajan para integrar
Cambios realizados

2018-10-21 16:18 UTC, estelleroques commented on 1-estrategia/README.md
> +Queremos que nuestros usuarios ingresen con inquietudes y salgan con ellas resueltas, es decir, cuando el migrante llega a su lugar de destino se encuentra en lo que denominaremos el punto cero, sin
Cambios realizados

2018-10-22 18:48 UTC, LisandroToledo approved these changes

2018-10-22 19:24 UTC, merged